language: go
go:
  - 1.8

notifications:
  email: false

env:
  global:
    - secure: "EQZvPcU3L1/HLNx4ncHWJbF1oQIUelGZungO7APBKxnX0oq//RQ0LXGoEeY8rgg2q8r3utyeg5yZlqZ9AtXymX0dJX/uAsA4HvuM28DKOuMXrdJh7gg43qQaHMecCF0nKNTbYRxxLrOcbRbmi0ZCAD18II3GqBSGGofHdCGULnZbwXCojJYeJzMaAmWjYNAXoP46MwqyFzicsZkROWGbajWERVfzSIqmI5zb2i9LlEszXi7xvrHphdukE3may2+VN39STVYYxoQBIc0FzaLkweanUB550SB/ZvB/9Za6vjSrlXxyGlb3l8NS41PP2OAVz0eZ3Xrsx6ZletrTShR8LMosrqqU+Ini0wAfTNAFOfSBS9PU34N9MHFh1OmxU584HPHEqfG9yZU/yE17lPgHaKSNz2a2wB0fvhy5Zb1+fV/VaCLT8sRBpLytFUOXdjtQdeO2kPlGEeO4w2fDnw1WAyIfLedcchxiRUcvqJ+VxFWR9Iw/eYzDtfZQSPdjvP7LLNy2Dehu/E+wcJ6CFLG/004fpuEudgZLuszAiJ6S95cNYguMxdPW90gQ7MolMLKyDFecTxTj2D9/RhP9c8yUzUq/hXHCOxja0pvPQAgEoErvqzCvuD+GWJaTPsuBYwWMwPTMT6DKWgpHB0hCgvBIktGIUe/Eg0RUmB8hJPhtB9o="
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/goccmack/gocc
  # TODO: Remove once https://github.com/golang/go/issues/18665 is resolved.
  - go get golang.org/x/arch/x86/x86asm
  - wget -O $HOME/gopath/src/golang.org/x/arch/x86/x86asm/tables.go https://raw.githubusercontent.com/mewpull/arch/master/x86/x86asm/tables.go
  # TODO: Remove once v0.2 of llir/llvm is released.
  - go get -d github.com/llir/llvm/ir
  - make -C $HOME/gopath/src/github.com/llir/llvm/asm/internal gen
  # Install NASM for test case generation.
  - sudo apt-get -qq update
  - sudo apt-get install -y nasm

install:
  - go get -t ./...

before_script:
  - export GOLINT_IGNORE="-not -wholename '*/internal/*' -not -name '*_string.go' -not -wholename '*/types/single.go' -not -wholename '*/types/types.go' -not -wholename '*/ir/function.go'"
  - wget https://gist.github.com/mewmew/379014c9a2e6885e238d/raw/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
